import { Language } from "../interfaces/interface";

const languages: Array<Language> = [

    { value: "auto", name: "Detect language" },
    { value: "en-EN", name: "English" },
    { value: "fr-FR", name: "French" },
    { value: "es-ES", name: "Spanish" },
    { value: "zu-ZA", name: "Zulu" },
    { value: "yi-YD", name: "Yiddish" },
    { value: "xh-ZA", name: "Xhosa" },
    { value: "wo-SN", name: "Wolof" },
    { value: "cy-GB", name: "Welsh" },
    { value: "wls-WF", name: "Wallisian" },
    { value: "vi-VN", name: "Vietnamese" },
    { value: "uz-UZ", name: "Uzbek" },
    { value: "ppk-ID", name: "Uma" },
    { value: "uk-UA", name: "Ukrainian" },
    { value: "tvl-TV", name: "Tuvaluan" },
    { value: "tk-TM", name: "Turkmen" },
    { value: "tr-TR", name: "Turkish" },
    { value: "tn-BW", name: "Tswana" },
    { value: "to-TO", name: "Tongan" },
    { value: "tkl-TK", name: "Tokelauan" },
    { value: "tpi-PG", name: "Tok Pisin" },
    { value: "ti-TI", name: "Tigrinya" },
    { value: "bo-CN", name: "Tibetan" },
    { value: "th-TH", name: "Thai" },
    { value: "tet-TL", name: "Tetum" },
    { value: "te-IN", name: "Telugu" },
    { value: "ta-LK", name: "Tamil" },
    { value: "tmh-DZ", name: "Tamashek (Tuareg)" },
    { value: "tg-TJ", name: "Tajik" },
    { value: "tl-PH", name: "Tagalog" },
    { value: "syc-TR", name: "Syriac (Aramaic)" },
    { value: "de-CH", name: "Swiss German" },
    { value: "sv-SE", name: "Swedish" },
    { value: "sw-SZ", name: "Swahili" },
    { value: "srn-SR", name: "Sranan Tongo" },
    { value: "st-ST", name: "Sotho, Southern" },
    { value: "so-SO", name: "Somali" },
    { value: "es-ES", name: "Spanish" },
    { value: "sl-SI", name: "Slovenian" },
    { value: "sk-SK", name: "Slovak" },
    { value: "si-LK", name: "Sinhala" },
    { value: "sn-ZW", name: "Shona" },
    { value: "sr-RS", name: "Serbian" },
    { value: "gd-GB", name: "Scots Gaelic" },
    { value: "sg-CF", name: "Sango" },
    { value: "sm-WS", name: "Samoan" },
    { value: "ru-RU", name: "Russian" },
    { value: "ro-RO", name: "Romanian" },
    { value: "qu-PE", name: "Quechua" },
    { value: "pot-US", name: "Potawatomi" },
    { value: "pt-PT", name: "Portuguese" },
    { value: "pl-PL", name: "Polish" },
    { value: "pis-SB", name: "Pijin" },
    { value: "fa-IR", name: "Persian" },
    { value: "ps-PK", name: "Pashto" },
    { value: "pap-CW", name: "Papiamentu" },
    { value: "pa-IN", name: "Panjabi" },
    { value: "pau-PW", name: "Palauan" },
    { value: "ur-PK", name: "Pakistani" },
    { value: "ny-MW", name: "Nyanja" },
    { value: "no-NO", name: "Norwegian" },
    { value: "niu-NU", name: "Niuean" },
    { value: "ne-NP", name: "Nepali" },
    { value: "mfe-MU", name: "Morisyen" },
    { value: "mn-MN", name: "Mongolian" },
    { value: "men-SL", name: "Mende" },
    { value: "mh-MH", name: "Marshallese" },
    { value: "mi-NZ", name: "Maori" },
    { value: "gv-IM", name: "Manx Gaelic" },
    { value: "mt-MT", name: "Maltese" },
    { value: "dv-MV", name: "Maldivian" },
    { value: "ms-MY", name: "Malay" },
    { value: "mg-MG", name: "Malagasy" },
    { value: "mk-MK", name: "Macedonian" },
    { value: "lb-LU", name: "Luxembourgish" },
    { value: "lt-LT", name: "Lithuanian" },
    { value: "lv-LV", name: "Latvian" },
    { value: "la-VA", name: "Latin" },
    { value: "lo-LA", name: "Lao" },
    { value: "ky-KG", name: "Kyrgyz" },
    { value: "ckb-IQ", name: "Kurdish Sorani" },
    { value: "ku-TR", name: "Kurdish" },
    { value: "ko-KR", name: "Korean" },
    { value: "rn-BI", name: "Kirundi" },
    { value: "rw-RW", name: "Kinyarwanda" },
    { value: "km-KM", name: "Khmer" },
    { value: "kk-KZ", name: "Kazakh" },
    { value: "kn-IN", name: "Kannada" },
    { value: "kab-DZ", name: "Kabylian" },
    { value: "kea-CV", name: "Kabuverdianu" },
    { value: "jv-ID", name: "Javanese" },
    { value: "ja-JP", name: "Japanese" },
    { value: "it-IT", name: "Italian" },
    { value: "ga-IE", name: "Irish Gaelic" },
    { value: "kl-GL", name: "Inuktitut (Greenlandic)" },
    { value: "id-ID", name: "Indonesian" },
    { value: "is-IS", name: "Icelandic" },
    { value: "hu-HU", name: "Hungarian" },
    { value: "hi-IN", name: "Hindi" },
    { value: "he-IL", name: "Hebrew" },
    { value: "haw-US", name: "Hawaiian" },
    { value: "ha-NE", name: "Hausa" },
    { value: "gu-IN", name: "Gujarati" },
    { value: "grc-GR", name: "Greek (Classical)" },
    { value: "el-GR", name: "Greek" },
    { value: "de-DE", name: "German" },
    { value: "ka-GE", name: "Georgian" },
    { value: "gl-ES", name: "Galician" },
    { value: "fi-FI", name: "Finnish" },
    { value: "fo-FO", name: "Faroese" },
    { value: "fn-FNG", name: "Fanagalo" },
    { value: "et-EE", name: "Estonian" },
    { value: "eo-EU", name: "Esperanto" },
    { value: "dz-BT", name: "Dzongkha" },
    { value: "nl-NL", name: "Dutch" },
    { value: "da-DK", name: "Danish" },
    { value: "cs-CZ", name: "Czech" },
    { value: "hr-HR", name: "Croatian" },
    { value: "pov-GW", name: "Creole Portuguese (Upper Guinea)" },
    { value: "crs-SC", name: "Creole French (Seselwa)" },
    { value: "acf-LC", name: "Creole French (Saint Lucian)" },
    { value: "ht-HT", name: "Creole French (Haitian)" },
    { value: "vic-US", name: "Creole English (Virgin Islands)" },
    { value: "svc-VC", name: "Creole English (Vincentian)" },
    { value: "jam-JM", name: "Creole English (Jamaican)" },
    { value: "gyn-GY", name: "Creole English (Guyanese)" },
    { value: "gcl-GD", name: "Creole English (Grenadian)" },
    { value: "bah-BS", name: "Creole English (Bahamas)" },
    { value: "aig-AG", name: "Creole English (Antigua and Barbuda)" },
    { value: "cop-EG", name: "Coptic" },
    { value: "zdj-KM", name: "Comorian (Ngazidja)" },
    { value: "zh-TW", name: "Chinese Traditional" },
    { value: "zh-CN", name: "Chinese (Simplified)" },
    { value: "ch-GU", name: "Chamorro" },
    { value: "ceb-PH", name: "Cebuano" },
    { value: "ca-ES", name: "Catalan" },
    { value: "my-MM", name: "Burmese" },
    { value: "bg-BG", name: "Bulgarian" },
    { value: "br-FR", name: "Breton" },
    { value: "bs-BA", name: "Bosnian" },
    { value: "bi-VU", name: "Bislama" },
    { value: "be-BY", name: "Bielarus" },
    { value: "bn-IN", name: "Bengali" },
    { value: "bem-ZM", name: "Bemba" },
    { value: "eu-ES", name: "Basque" },
    { value: "rm-RO", name: "Balkan Gipsy" },
    { value: "bjs-BB", name: "Bajan" },
    { value: "az-AZ", name: "Azerbaijani" },
    { value: "hy-AM", name: "Armenian" },
    { value: "ar-SA", name: "Arabic" },
    { value: "am-ET", name: "Amharic" },
    { value: "sq-AL", name: "Albanian" },
    { value: "af-ZA", name: "Afrikaans" },]

export default languages;